
import java.io.*; 
import javax.swing.*; 
import java.awt.event.*; 
import javax.swing.filechooser.*;
/**
 *
 * @author gokse
 */
public class Otomasyon extends javax.swing.JFrame {
double [] icecekler=new double[7];
double [] tatlilar=new double[7];
String [] fiyat=new String[3];
double [] i=new double[14];
double bahsis;
double tatlilartoplam;
double iceceklertoplam;
double ekmekkadayififiyat= 10;
double mozaikpastafiyat= 6;
double cheesscakefiyat= 6;
double supanglefiyat= 5;
double cayfiyat= 2;
double turkkahvesifiyat= 5;
double americanofiyat= 6.5;
double lattefiyat= 7;
double limonatafiyat= 3.5;
double milkshakefiyat= 12;
double mojitofiyat= 10;
double sutlukadayiffiyat= 14;
double kemalpasafiyat= 9;
double kabaktatlisifiyat= 8;
double sonuc;
double firstnum;
double secondnum;
String operation;



    
    
    public Otomasyon() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sutlukadayif = new javax.swing.JCheckBox();
        kemalpasa = new javax.swing.JCheckBox();
        kabaktatlisi = new javax.swing.JCheckBox();
        ekmekkadayifi = new javax.swing.JCheckBox();
        mozaikpasta = new javax.swing.JCheckBox();
        cheesscake = new javax.swing.JCheckBox();
        supangle = new javax.swing.JCheckBox();
        cay = new javax.swing.JCheckBox();
        turkkahvesi = new javax.swing.JCheckBox();
        americano = new javax.swing.JCheckBox();
        latte = new javax.swing.JCheckBox();
        limonata = new javax.swing.JCheckBox();
        milkshake = new javax.swing.JCheckBox();
        mojito = new javax.swing.JCheckBox();
        txt_sutlukadayif = new javax.swing.JTextField();
        txt_kemalpasa = new javax.swing.JTextField();
        txt_kabaktatlisi = new javax.swing.JTextField();
        txt_ekmekkadayifi = new javax.swing.JTextField();
        txt_mozaikpasta = new javax.swing.JTextField();
        txt_cheesscake = new javax.swing.JTextField();
        txt_supangle = new javax.swing.JTextField();
        txt_cay = new javax.swing.JTextField();
        txt_turkkahvesi = new javax.swing.JTextField();
        txt_americano = new javax.swing.JTextField();
        txt_latte = new javax.swing.JTextField();
        txt_limonata = new javax.swing.JTextField();
        txt_milkshake = new javax.swing.JTextField();
        txt_mojito = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        btnce = new javax.swing.JButton();
        ekran = new javax.swing.JTextField();
        btnc = new javax.swing.JButton();
        btnbckspc = new javax.swing.JButton();
        btndivided = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnmultiple = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnminus = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnplus = new javax.swing.JButton();
        btnposneg = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btnequal = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        faturaalan = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_iceceklertoplam = new javax.swing.JTextField();
        txt_tatlilartoplam = new javax.swing.JTextField();
        txt_bahsis = new javax.swing.JTextField();
        txt_bruttoplam = new javax.swing.JTextField();
        txt_kdv = new javax.swing.JTextField();
        txt_nettoplam = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        toplam = new javax.swing.JButton();
        fatura = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        kapat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KAFE YÖNETİM OTOMASYONU");

        sutlukadayif.setText("Sütlü Kadayıf");
        sutlukadayif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sutlukadayifMouseClicked(evt);
            }
        });

        kemalpasa.setText("Kemal Paşa");
        kemalpasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kemalpasaMouseClicked(evt);
            }
        });

        kabaktatlisi.setText("Kabak Tatlısı");
        kabaktatlisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kabaktatlisiMouseClicked(evt);
            }
        });

        ekmekkadayifi.setText("Ekmek Kadayıf");
        ekmekkadayifi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ekmekkadayifiMouseClicked(evt);
            }
        });

        mozaikpasta.setText("Mozaik Pasta");
        mozaikpasta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mozaikpastaMouseClicked(evt);
            }
        });

        cheesscake.setText("Cheesscake");
        cheesscake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cheesscakeMouseClicked(evt);
            }
        });

        supangle.setText("Supangle");
        supangle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supangleMouseClicked(evt);
            }
        });

        cay.setText("Çay");
        cay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cayMouseClicked(evt);
            }
        });

        turkkahvesi.setText("Türk Kahvesi");
        turkkahvesi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turkkahvesiMouseClicked(evt);
            }
        });

        americano.setText("Americano");
        americano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                americanoMouseClicked(evt);
            }
        });

        latte.setText("Latte");
        latte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                latteMouseClicked(evt);
            }
        });

        limonata.setText("Limonata");
        limonata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limonataMouseClicked(evt);
            }
        });

        milkshake.setText("Milkshake");
        milkshake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                milkshakeMouseClicked(evt);
            }
        });

        mojito.setText("Mojito");
        mojito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mojitoMouseClicked(evt);
            }
        });

        txt_sutlukadayif.setText("0");

        txt_kemalpasa.setText("0");

        txt_kabaktatlisi.setText("0");

        txt_ekmekkadayifi.setText("0");

        txt_mozaikpasta.setText("0");

        txt_cheesscake.setText("0");

        txt_supangle.setText("0");

        txt_turkkahvesi.setText("0");

        txt_americano.setText("0");

        txt_latte.setText("0");

        txt_limonata.setText("0");

        txt_milkshake.setText("0");

        txt_mojito.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kemalpasa)
                    .addComponent(sutlukadayif)
                    .addComponent(kabaktatlisi)
                    .addComponent(supangle)
                    .addComponent(cheesscake)
                    .addComponent(mozaikpasta)
                    .addComponent(ekmekkadayifi))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_cheesscake, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_mozaikpasta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_ekmekkadayifi)
                    .addComponent(txt_kabaktatlisi)
                    .addComponent(txt_kemalpasa)
                    .addComponent(txt_sutlukadayif, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_supangle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(turkkahvesi)
                    .addComponent(cay)
                    .addComponent(americano)
                    .addComponent(latte)
                    .addComponent(limonata)
                    .addComponent(milkshake)
                    .addComponent(mojito))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_cay, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_turkkahvesi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_americano, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_latte, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_limonata, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_milkshake, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_mojito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sutlukadayif)
                    .addComponent(cay)
                    .addComponent(txt_sutlukadayif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kemalpasa)
                    .addComponent(turkkahvesi)
                    .addComponent(txt_kemalpasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_turkkahvesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kabaktatlisi)
                    .addComponent(americano)
                    .addComponent(txt_kabaktatlisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_americano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekmekkadayifi)
                    .addComponent(latte)
                    .addComponent(txt_ekmekkadayifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_latte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mozaikpasta)
                    .addComponent(limonata)
                    .addComponent(txt_mozaikpasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_limonata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheesscake)
                    .addComponent(milkshake)
                    .addComponent(txt_cheesscake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_milkshake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supangle)
                    .addComponent(mojito)
                    .addComponent(txt_supangle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mojito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnce.setText("CE");
        btnce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceActionPerformed(evt);
            }
        });

        ekran.setText("0");

        btnc.setText("C");

        btnbckspc.setText("←");
        btnbckspc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbckspcActionPerformed(evt);
            }
        });

        btndivided.setText("÷");
        btndivided.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndividedActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnmultiple.setText("x");
        btnmultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultipleActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btnminus.setText("-");
        btnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminusActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnplus.setText("+");
        btnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplusActionPerformed(evt);
            }
        });

        btnposneg.setText("+ -");

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btndot.setText(".");
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });

        btnequal.setText("=");
        btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ekran)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnposneg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnce, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnbckspc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndivided, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnminus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnplus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnequal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ekran, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnce, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbckspc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndivided, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnminus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnplus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnposneg, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnequal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hesap Makinesi", jPanel5);

        faturaalan.setColumns(20);
        faturaalan.setRows(5);
        jScrollPane1.setViewportView(faturaalan);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fatura", jPanel6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jLabel2.setText("İçecekler Toplamı");

        jLabel3.setText("Tatlılar Toplamı");

        jLabel4.setText("Bahşiş");

        jLabel5.setText("Brüt Toplam");

        jLabel6.setText("KDV");

        jLabel7.setText("Net Toplam");

        txt_iceceklertoplam.setText("0");
        txt_iceceklertoplam.setEnabled(false);

        txt_tatlilartoplam.setText("0");
        txt_tatlilartoplam.setEnabled(false);

        txt_bahsis.setText("0");
        txt_bahsis.setEnabled(false);

        txt_bruttoplam.setText("0");
        txt_bruttoplam.setEnabled(false);

        txt_kdv.setText("0");
        txt_kdv.setEnabled(false);

        txt_nettoplam.setText("0");
        txt_nettoplam.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nettoplam, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txt_kdv)
                    .addComponent(txt_bruttoplam)
                    .addComponent(txt_bahsis)
                    .addComponent(txt_tatlilartoplam)
                    .addComponent(txt_iceceklertoplam, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_iceceklertoplam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tatlilartoplam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_bahsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_bruttoplam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_kdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_nettoplam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        toplam.setText("Toplam");
        toplam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toplamMouseClicked(evt);
            }
        });

        fatura.setText("Fatura");
        fatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faturaMouseClicked(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        kapat.setText("Kapat");
        kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapatActionPerformed(evt);
            }
        });

        jButton1.setText("PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toplam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kapat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toplam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(fatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kapat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sutlukadayifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sutlukadayifMouseClicked
        double sutlukadayifadet=Double.parseDouble(txt_sutlukadayif.getText());
        if (sutlukadayif.isSelected()) {
            i[0]=(sutlukadayifadet*sutlukadayiffiyat);
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_sutlukadayif.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[0]=0;
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_sutlukadayif.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_sutlukadayifMouseClicked

    private void kemalpasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kemalpasaMouseClicked
        double kemalpasaadet=Double.parseDouble(txt_kemalpasa.getText());
        if (kemalpasa.isSelected()) {
            i[1]=(kemalpasaadet*kemalpasafiyat);
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_kemalpasa.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[1]=0;
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_kemalpasa.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_kemalpasaMouseClicked

    private void kabaktatlisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kabaktatlisiMouseClicked
        double kabaktatlisiadet=Double.parseDouble(txt_kabaktatlisi.getText());
        if (kabaktatlisi.isSelected()) {
            i[2]=(kabaktatlisiadet*kabaktatlisifiyat);
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_kabaktatlisi.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[2]=0;
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_kabaktatlisi.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_kabaktatlisiMouseClicked

    private void ekmekkadayifiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekmekkadayifiMouseClicked
        double ekmekkadayifiadet=Double.parseDouble(txt_ekmekkadayifi.getText());
        if (ekmekkadayifi.isSelected()) {
            i[3]=(ekmekkadayifiadet*ekmekkadayififiyat);
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_ekmekkadayifi.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[3]=0;
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_ekmekkadayifi.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_ekmekkadayifiMouseClicked

    private void mozaikpastaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mozaikpastaMouseClicked
        double mozaikpastaadet=Double.parseDouble(txt_mozaikpasta.getText());
        if (mozaikpasta.isSelected()) {
            i[4]=(mozaikpastaadet*mozaikpastafiyat);
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_mozaikpasta.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[4]=0;
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_mozaikpasta.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_mozaikpastaMouseClicked

    private void cheesscakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cheesscakeMouseClicked
        double cheesscakeadet=Double.parseDouble(txt_cheesscake.getText());
        if (cheesscake.isSelected()) {
            i[5]=(cheesscakeadet*cheesscakefiyat);
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_cheesscake.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[5]=0;
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_cheesscake.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_cheesscakeMouseClicked

    private void supangleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supangleMouseClicked
        double supangleadet=Double.parseDouble(txt_supangle.getText());
        if (supangle.isSelected()) {
            i[6]=(supangleadet*supanglefiyat);
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_supangle.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[6]=0;
            tatlilartoplam=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(tatlilartoplam);
            txt_tatlilartoplam.setText(tat);
            txt_supangle.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_supangleMouseClicked

    private void cayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cayMouseClicked
        double cayadet=Double.parseDouble(txt_cay.getText());
        if (cay.isSelected()) {
            i[7]=(cayadet*cayfiyat);
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_cay.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[7]=0;
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_cay.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_cayMouseClicked

    private void turkkahvesiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turkkahvesiMouseClicked
        double turkkahvesiadet=Double.parseDouble(txt_turkkahvesi.getText());
        if (turkkahvesi.isSelected()) {
            i[8]=(turkkahvesiadet*turkkahvesifiyat);
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_turkkahvesi.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[8]=0;
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_turkkahvesi.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_turkkahvesiMouseClicked

    private void americanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_americanoMouseClicked
        double americanoadet=Double.parseDouble(txt_americano.getText());
        if (americano.isSelected()) {
            i[9]=(americanoadet*americanofiyat);
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_americano.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[9]=0;
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_americano.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_americanoMouseClicked

    private void latteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_latteMouseClicked
        double latteadet=Double.parseDouble(txt_latte.getText());
        if (latte.isSelected()) {
            i[10]=(latteadet*lattefiyat);
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_latte.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[10]=0;
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_latte.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_latteMouseClicked

    private void limonataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limonataMouseClicked
        double limonataadet=Double.parseDouble(txt_limonata.getText());
        if (limonata.isSelected()) {
            i[11]=(limonataadet*limonatafiyat);
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);

            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_limonata.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[11]=0;
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);

            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_limonata.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_limonataMouseClicked

    private void milkshakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milkshakeMouseClicked
        double milkshakeadet=Double.parseDouble(txt_milkshake.getText());
        if (milkshake.isSelected()) {
            i[12]=(milkshakeadet*milkshakefiyat);
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);

            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_milkshake.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[12]=0;
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);

            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_milkshake.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_milkshakeMouseClicked

    private void mojitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mojitoMouseClicked
        double mojitoadet=Double.parseDouble(txt_mojito.getText());
        if (mojito.isSelected()) {
            i[13]=(mojitoadet*mojitofiyat);
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);

            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_mojito.setEnabled(false);
            double  fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
        }
        else
        {

            i[13]=0;
            iceceklertoplam=(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            bahsis=(i[0])+(i[1])+(i[2])+(i[3])+(i[4])+(i[5])+(i[6])+(i[7])+(i[8])+(i[9])+(i[10])+(i[11])+(i[12])+(i[13]);
            String tat=Double.toString(iceceklertoplam);
            txt_iceceklertoplam.setText(tat);
            txt_mojito.setEnabled(true);

            double fbahsis=(bahsis*0.01);
            String pBahsis=Double.toString(fbahsis);
            txt_bahsis.setText(pBahsis);
            
        }
    }//GEN-LAST:event_mojitoMouseClicked

    private void toplamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toplamMouseClicked
        double tatli=Double.parseDouble(txt_tatlilartoplam.getText());
        double icecek=Double.parseDouble(txt_iceceklertoplam.getText());
        double bahsistoplam=Double.parseDouble(txt_bahsis.getText());
        double brutToplam=tatli+icecek+bahsistoplam;
        double kdv=brutToplam*0.18;
        double netToplam=kdv+brutToplam;

        String fbrut=Double.toString(brutToplam);
        String fkdv=Double.toString(kdv);
        String fnet=Double.toString(netToplam);                
        txt_bruttoplam.setText(fbrut);
        txt_kdv.setText(fkdv);
        txt_nettoplam.setText(fnet);
    }//GEN-LAST:event_toplamMouseClicked

    private void faturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faturaMouseClicked
        fiyat[0]=txt_kdv.getText();
        fiyat[1]=txt_bruttoplam.getText();
        fiyat[2]=txt_nettoplam.getText();
        
        faturaalan.append(" \t\n Kafe Otomasyon Sistemi:\n\n");
                if (cay.isSelected()) {
                icecekler[0]=Double.parseDouble(txt_cay.getText());
                faturaalan.append("Çay:\t\t "+icecekler[0]*cayfiyat+" TL \n");
                 }
                if (turkkahvesi.isSelected()) {
                icecekler[1]=Double.parseDouble(txt_turkkahvesi.getText());
                faturaalan.append("Türk Kahvesi:\t\t "+icecekler[1]*turkkahvesifiyat+" TL \n");
                 }
                if (americano.isSelected()) {
                icecekler[2]=Double.parseDouble(txt_americano.getText());
                faturaalan.append("Americano:\t\t "+icecekler[2]*americanofiyat+" TL \n");
                 }
                if (latte.isSelected()) {
                icecekler[3]=Double.parseDouble(txt_latte.getText());
                faturaalan.append("Latte:\t\t "+icecekler[3]*lattefiyat+" TL \n");
                 }
                if (limonata.isSelected()) {
                icecekler[4]=Double.parseDouble(txt_limonata.getText());
                faturaalan.append("Limonata:\t\t "+icecekler[4]*limonatafiyat+" TL \n");
                 }
                if (milkshake.isSelected()) {
                icecekler[5]=Double.parseDouble(txt_milkshake.getText());
                faturaalan.append("Milkshake:\t\t "+icecekler[5]*milkshakefiyat+" TL \n");
                 }
                if (mojito.isSelected()) {
                icecekler[6]=Double.parseDouble(txt_mojito.getText());
                faturaalan.append("Mojito:\t\t "+icecekler[6]*mojitofiyat+" TL \n");
                 }
                if (sutlukadayif.isSelected()) {
                tatlilar[0]=Double.parseDouble(txt_sutlukadayif.getText());
                faturaalan.append("Sütlü Kadayıf:\t\t "+tatlilar[0]*sutlukadayiffiyat+" TL \n");
                 }
                if (kemalpasa.isSelected()) {
                tatlilar[1]=Double.parseDouble(txt_kemalpasa.getText());
                faturaalan.append("Kemal Paşa:\t\t "+tatlilar[1]*kemalpasafiyat+" TL \n");
                 }
                if (kabaktatlisi.isSelected()) {
                tatlilar[2]=Double.parseDouble(txt_kabaktatlisi.getText());
                faturaalan.append("Kabak Tatlısı:\t\t "+tatlilar[2]*kabaktatlisifiyat+ "TL \n");
                 }
                if (ekmekkadayifi.isSelected()) {
                tatlilar[3]=Double.parseDouble(txt_ekmekkadayifi.getText());
                faturaalan.append("Ekmek Kadayıfı:\t\t "+tatlilar[3]*ekmekkadayififiyat+" TL \n");
                 }
                if (mozaikpasta.isSelected()) {
                tatlilar[4]=Double.parseDouble(txt_mozaikpasta.getText());
                faturaalan.append("Mozaik Pasta:\t\t "+tatlilar[4]*mozaikpastafiyat+" TL \n");
                 }
                if (cheesscake.isSelected()) {
                tatlilar[5]=Double.parseDouble(txt_cheesscake.getText());
                faturaalan.append("Dondurma:\t\t "+tatlilar[5]*cheesscakefiyat+" TL \n");
                 }
                if (supangle.isSelected()) {
                tatlilar[6]=Double.parseDouble(txt_supangle.getText());
                faturaalan.append("Supangle:\t\t "+tatlilar[6]*supanglefiyat+" TL \n");
                 }
                faturaalan.append("KDV:\t\t "+fiyat[0]+" TL \n Brüt Toplam:\t\t "+fiyat[1]+" TL \n Net Toplam:\t\t "+fiyat[2]+" TL");
        
    }//GEN-LAST:event_faturaMouseClicked

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String deger= ekran.getText()+btn0.getText();
        ekran.setText(deger);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String deger= ekran.getText()+btn1.getText();
        ekran.setText(deger);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String deger= ekran.getText()+btn2.getText();
        ekran.setText(deger);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String deger= ekran.getText()+btn3.getText();
        ekran.setText(deger);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String deger= ekran.getText()+btn4.getText();
        ekran.setText(deger);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String deger= ekran.getText()+btn5.getText();
        ekran.setText(deger);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String deger= ekran.getText()+btn6.getText();
        ekran.setText(deger);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String deger= ekran.getText()+btn7.getText();
        ekran.setText(deger);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String deger= ekran.getText()+btn8.getText();
        ekran.setText(deger);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String deger= ekran.getText()+btn9.getText();
        ekran.setText(deger);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnbckspcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbckspcActionPerformed
        String deger=ekran.getText();
        String metin=null;
        if(deger.length()>0) 
        {
            StringBuffer str= new StringBuffer(ekran.getText());
            str.deleteCharAt(ekran.getText().length()-1);
            metin=str.toString();
            ekran.setText(metin);
        }
    }//GEN-LAST:event_btnbckspcActionPerformed

    private void btnceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceActionPerformed
        ekran.setText(null);
        sonuc=0;
    }//GEN-LAST:event_btnceActionPerformed

    private void btnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusActionPerformed
        firstnum= Double.parseDouble(ekran.getText());
        ekran.setText("");
        operation="+";
    }//GEN-LAST:event_btnplusActionPerformed

    private void btnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminusActionPerformed
        firstnum= Double.parseDouble(ekran.getText());
        ekran.setText("");
        operation="-";
    }//GEN-LAST:event_btnminusActionPerformed

    private void btnmultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultipleActionPerformed
        firstnum= Double.parseDouble(ekran.getText());
        ekran.setText("");
        operation="*";
    }//GEN-LAST:event_btnmultipleActionPerformed

    private void btndividedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndividedActionPerformed
        firstnum= Double.parseDouble(ekran.getText());
        ekran.setText("");
        operation="/";
    }//GEN-LAST:event_btndividedActionPerformed

    private void btnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalActionPerformed
        secondnum=Double.parseDouble(ekran.getText());
        if (operation=="+") {
            sonuc=firstnum+secondnum;
        }
        else if (operation=="-") {
            sonuc=firstnum-secondnum;
        }
        else if (operation=="*") {
            sonuc=firstnum*secondnum;
        }
        else if (operation=="/") {
            sonuc=firstnum/secondnum;
        }
        else if (operation=="%") {
            sonuc=firstnum-secondnum;
        }
        String tsonuc=Double.toString(sonuc);
        ekran.setText(tsonuc);
    }//GEN-LAST:event_btnequalActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
        StringBuffer strB=new StringBuffer(ekran.getText());
        if (strB.indexOf(".")<0) {
            String deger= ekran.getText()+btndot.getText();
            ekran.setText(deger);}
    }//GEN-LAST:event_btndotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JFileChooser saver = new JFileChooser("./");
    int returnVal = saver.showSaveDialog(this);
    File file = saver.getSelectedFile();
    BufferedWriter writer = null;
    if (returnVal == JFileChooser.APPROVE_OPTION)
    {
    try
    {
    writer = new BufferedWriter( new FileWriter( file.getAbsolutePath()+".txt"));
    writer.write( faturaalan.getText());
    writer.close( );
    JOptionPane.showMessageDialog(this, "The Message was Saved Successfully!",
                "Success!", JOptionPane.INFORMATION_MESSAGE);
    }
    catch (IOException e)
    {
    JOptionPane.showMessageDialog(this, "The Text could not be Saved!",
                "Error!", JOptionPane.INFORMATION_MESSAGE);
    }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        txt_cay.setText("0");
        txt_americano.setText("0");
        txt_turkkahvesi.setText("0");
        txt_latte.setText("0");
        txt_limonata.setText("0");
        txt_milkshake.setText("0");
        txt_mojito.setText("0");
        txt_sutlukadayif.setText("0");
        txt_kemalpasa.setText("0");
        txt_kabaktatlisi.setText("0");
        txt_ekmekkadayifi.setText("0");
        txt_mozaikpasta.setText("0");
        txt_cheesscake.setText("0");
        txt_supangle.setText("0");
        txt_tatlilartoplam.setText("0");
        txt_nettoplam.setText("0");
        txt_kdv.setText("0");
        txt_bruttoplam.setText("0");
        txt_iceceklertoplam.setText("0");
        txt_bahsis.setText("0");
        ekran.setText("0");
        faturaalan.setText("");
        sutlukadayif.setSelected(false);
        cay.setSelected(false);
        cheesscake.setSelected(false);
        ekmekkadayifi.setSelected(false);
        kabaktatlisi.setSelected(false);
        kemalpasa.setSelected(false);
        latte.setSelected(false);
        limonata.setSelected(false);
        milkshake.setSelected(false);
        mojito.setSelected(false);
        mozaikpasta.setSelected(false);
        supangle.setSelected(false);
        turkkahvesi.setSelected(false);
        americano.setSelected(false);
        txt_cay.setEnabled(true);
        txt_americano.setEnabled(true);
        txt_turkkahvesi.setEnabled(true);
        txt_latte.setEnabled(true);
        txt_limonata.setEnabled(true);
        txt_milkshake.setEnabled(true);
        txt_mojito.setEnabled(true);
        txt_sutlukadayif.setEnabled(true);
        txt_kemalpasa.setEnabled(true);
        txt_kabaktatlisi.setEnabled(true);
        txt_ekmekkadayifi.setEnabled(true);
        txt_mozaikpasta.setEnabled(true);
        txt_cheesscake.setEnabled(true);
        txt_supangle.setEnabled(true);
        
        

    }//GEN-LAST:event_resetActionPerformed

    private void kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_kapatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Otomasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Otomasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Otomasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Otomasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Otomasyon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox americano;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnbckspc;
    private javax.swing.JButton btnc;
    private javax.swing.JButton btnce;
    private javax.swing.JButton btndivided;
    private javax.swing.JButton btndot;
    private javax.swing.JButton btnequal;
    private javax.swing.JButton btnminus;
    private javax.swing.JButton btnmultiple;
    private javax.swing.JButton btnplus;
    private javax.swing.JButton btnposneg;
    private javax.swing.JCheckBox cay;
    private javax.swing.JCheckBox cheesscake;
    private javax.swing.JCheckBox ekmekkadayifi;
    private javax.swing.JTextField ekran;
    private javax.swing.JButton fatura;
    private javax.swing.JTextArea faturaalan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox kabaktatlisi;
    private javax.swing.JButton kapat;
    private javax.swing.JCheckBox kemalpasa;
    private javax.swing.JCheckBox latte;
    private javax.swing.JCheckBox limonata;
    private javax.swing.JCheckBox milkshake;
    private javax.swing.JCheckBox mojito;
    private javax.swing.JCheckBox mozaikpasta;
    private javax.swing.JButton reset;
    private javax.swing.JCheckBox supangle;
    private javax.swing.JCheckBox sutlukadayif;
    private javax.swing.JButton toplam;
    private javax.swing.JCheckBox turkkahvesi;
    private javax.swing.JTextField txt_americano;
    private javax.swing.JTextField txt_bahsis;
    private javax.swing.JTextField txt_bruttoplam;
    private javax.swing.JTextField txt_cay;
    private javax.swing.JTextField txt_cheesscake;
    private javax.swing.JTextField txt_ekmekkadayifi;
    private javax.swing.JTextField txt_iceceklertoplam;
    private javax.swing.JTextField txt_kabaktatlisi;
    private javax.swing.JTextField txt_kdv;
    private javax.swing.JTextField txt_kemalpasa;
    private javax.swing.JTextField txt_latte;
    private javax.swing.JTextField txt_limonata;
    private javax.swing.JTextField txt_milkshake;
    private javax.swing.JTextField txt_mojito;
    private javax.swing.JTextField txt_mozaikpasta;
    private javax.swing.JTextField txt_nettoplam;
    private javax.swing.JTextField txt_supangle;
    private javax.swing.JTextField txt_sutlukadayif;
    private javax.swing.JTextField txt_tatlilartoplam;
    private javax.swing.JTextField txt_turkkahvesi;
    // End of variables declaration//GEN-END:variables
}
